using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Input;
using DevExpress.XtraEditors;
using System.Windows.Forms;
using System.Drawing;
using System.Diagnostics;
using DevExpress.XtraMap;
using static System.ComponentModel.Design.ObjectSelectorEditor;
using System.Data;

namespace VoteToHead
{
    public partial class Form3 : DevExpress.XtraEditors.XtraForm
    {
        SqlConnection con = new SqlConnection("Data Source=(LocalDB)\\MSSQLLocalDB;AttachDbFilename='|DataDirectory|\\Database\\VTDatabase.mdf';Integrated Security=True");
        SqlCommand cmd = new SqlCommand();
        //SqlDataReader dr;
        SqlParameter picture;

        public Form3()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            //candidateTableAdapter6.Fill(report1.Candidate);
        }

        #region textbox place holder text

        public void Text1GotFocus(object sender, EventArgs e)
        {

            TextBox tb = (TextBox)sender;
            if (tb.Text == "Candidate Head Boy 1")
            {
                tb.Text = "";
                tb.ForeColor = Color.Black;
            }
        }

        public void Text1LostFocus(object sender, EventArgs e)
        {
            TextBox tb = (TextBox)sender;
            if (tb.Text == "")
            {
                tb.Text = "Candidate Head Boy 1";
                tb.ForeColor = Color.Gray;
            }
        }

        public void Text2GotFocus(object sender, EventArgs e)
        {
            TextBox tb = (TextBox)sender;
            if (tb.Text == "Candidate Head Boy 2")
            {
                tb.Text = "";
                tb.ForeColor = Color.Black;
            }
        }

        public void Text2LostFocus(object sender, EventArgs e)
        {
            TextBox tb = (TextBox)sender;
            if (tb.Text == "")
            {
                tb.Text = "Candidate Head Boy 2";
                tb.ForeColor = Color.Gray;
            }
        }

        public void Text3GotFocus(object sender, EventArgs e)
        {

            TextBox tb = (TextBox)sender;
            if (tb.Text == "Candidate Head Boy 3")
            {
                tb.Text = "";
                tb.ForeColor = Color.Black;
            }
        }

        public void Text3LostFocus(object sender, EventArgs e)
        {
            TextBox tb = (TextBox)sender;
            if (tb.Text == "")
            {
                tb.Text = "Candidate Head Boy 3";
                tb.ForeColor = Color.Gray;
            }
        }

        public void Text4GotFocus(object sender, EventArgs e)
        {
            TextBox tb = (TextBox)sender;
            if (tb.Text == "Candidate Head Girl 1")
            {
                tb.Text = "";
                tb.ForeColor = Color.Black;
            }
        }

        public void Text4LostFocus(object sender, EventArgs e)
        {
            TextBox tb = (TextBox)sender;
            if (tb.Text == "")
            {
                tb.Text = "Candidate Head Girl 1";
                tb.ForeColor = Color.Gray;
            }
        }

        public void Text5GotFocus(object sender, EventArgs e)
        {

            TextBox tb = (TextBox)sender;
            if (tb.Text == "Candidate Head Girl 2")
            {
                tb.Text = "";
                tb.ForeColor = Color.Black;
            }
        }

        public void Text5LostFocus(object sender, EventArgs e)
        {
            TextBox tb = (TextBox)sender;
            if (tb.Text == "")
            {
                tb.Text = "Candidate Head Girl 2";
                tb.ForeColor = Color.Gray;
            }
        }

        public void Text6GotFocus(object sender, EventArgs e)
        {
            TextBox tb = (TextBox)sender;
            if (tb.Text == "Candidate Head Girl 3")
            {
                tb.Text = "";
                tb.ForeColor = Color.Black;
            }
        }

        public void Text6LostFocus(object sender, EventArgs e)
        {
            TextBox tb = (TextBox)sender;
            if (tb.Text == "")
            {
                tb.Text = "Candidate Head Girl 3";
                tb.ForeColor = Color.Gray;
            }
        }

        #endregion

        #region Buttons

        private void btnLogout_Click(object sender, EventArgs e)
        {
            Form1 f1 = new Form1();
            MessageBox.Show("Successfully logged out!");
            this.Close();
            f1.Show();
        }

        private void btnLoadImage_Click(object sender, EventArgs e)
        {
            LoadPicture();
        }

        // string variable to save gender

        private void btnAddStd_Click(object sender, EventArgs e)
        {
            string gender = "Not Specified";
            Regex rgx = new Regex("[a-zA-Z]{4,}(?: [a-zA-Z]+){0,2}$");
            if (rgx.IsMatch(txtName.Text) && rgx.IsMatch(txtFatherName.Text) && (!string.IsNullOrEmpty(txtErpNo.Text) && !string.IsNullOrEmpty(txtClass.Text)))
            {
                // check for male-female
                if (rdMale.Checked)
                {
                    gender = "Male";
                }
                else if (rdFemale.Checked)
                {
                    gender = "Female";
                }

                // invoke a method to add student in database
                SaveData(gender);

                // clear the text boxes 
                txtName.Text = "";
                txtFatherName.Text = "";
                txtErpNo.Text = "";
                txtClass.Text = "";
            }
            else { MessageBox.Show("Error! Please fill the form.\nThese fields are required."); }
        }
        #endregion

        private void Form3_Load(object sender, EventArgs e)
        {
           /*
            // TODO: This line of code loads data into the 'dataSet2.Candidate' table. You can move, or remove it, as needed.
            this.candidateTableAdapter.Fill(this.dataSet2.Candidate);
            // TODO: This line of code loads data into the 'dataSet2.Candidate' table. You can move, or remove it, as needed.
            this.candidateTableAdapter.Fill(this.dataSet2.Candidate);
            // TODO: This line of code loads data into the 'dataSet1.Student' table. You can move, or remove it, as needed.
            this.studentTableAdapter1.Fill(this.dataSet1.Student);
            */
            // load sql parameter
            picture = new SqlParameter("@Photo", SqlDbType.Image);

            // TODO: This line of code loads data into the 'msdbDataSet2.Student' table. You can move, or remove it, as needed.
            //this.studentTableAdapter1.Fill(this.msdbDataSet2.Student);
            this.ActiveControl = label1;

            /*
            // candidate 1
            txtCan1.GotFocus += new EventHandler(this.Text1GotFocus);
            txtCan1.LostFocus += new EventHandler(this.Text1LostFocus);

            // candidate 2
            txtCan2.GotFocus += new EventHandler(this.Text2GotFocus);
            txtCan2.LostFocus += new EventHandler(this.Text2LostFocus);

            // candidate 3
            txtCan3.GotFocus += new EventHandler(this.Text3GotFocus);
            txtCan3.LostFocus += new EventHandler(this.Text3LostFocus);

            // candidate 4
            txtCan4.GotFocus += new EventHandler(this.Text4GotFocus);
            txtCan4.LostFocus += new EventHandler(this.Text4LostFocus);

            // candidate 5
            txtCan5.GotFocus += new EventHandler(this.Text5GotFocus);
            txtCan5.LostFocus += new EventHandler(this.Text5LostFocus);

            // candidate 6
            txtCan6.GotFocus += new EventHandler(this.Text6GotFocus);
            txtCan6.LostFocus += new EventHandler(this.Text6LostFocus);
        */}

        #region Methods
        // write a method to load picture
        private void LoadPicture()
        {
            try
            {
                OpenFileDialog of = new OpenFileDialog();
                of.InitialDirectory = "C:/Picture/";
                of.Filter = "All Files|*.*|JPEG|*.jpg|Bitmaps|*.bmp|GIFs|*.gif|PNG|*.png";
                of.FilterIndex = 2;
                of.Multiselect = false;
                if (of.ShowDialog() == DialogResult.OK)
                {
                    pictureBoxStdPhoto.Image = Image.FromFile(of.FileName);
                    pictureBoxStdPhoto.SizeMode = PictureBoxSizeMode.StretchImage;
                    pictureBoxStdPhoto.BorderStyle = BorderStyle.Fixed3D;

                }
            }
            catch (Exception ex) { MessageBox.Show(ex.ToString()); }
        }

        // write method to save data
        private void SaveData(string gender)
        {
            if (pictureBoxStdPhoto.Image != null)
            {
                MemoryStream ms = new MemoryStream();
                pictureBoxStdPhoto.Image.Save(ms, pictureBoxStdPhoto.Image.RawFormat);
                byte[] stdImg = ms.GetBuffer();
                ms.Close();

                // save data into db
                cmd.Connection = con;
                cmd.Parameters.Clear();
                cmd.Parameters.AddWithValue("@Photo", stdImg);
                cmd.CommandText = "insert into Table(Name,ErpNo,Class,Gender,Photo,EventTime) values('" + txtName.Text + "','" + txtErpNo.Text + "','" + txtClass.Text + "','" + gender + "', @Photo,'" + DateTime.Now + "')";
                con.Open();
                cmd.ExecuteNonQuery();
                con.Close();

                // interact with user by a message of success
                MessageBox.Show("Success! Student Record Added to the Database.");

                // clear picturebox
                pictureBoxStdPhoto.Image = null;
                
            }
        }

        private void btnRefresh_Click(object sender, EventArgs e)
        {
            Form4 f4 = new Form4();
            //this.Hide();
            f4.Show();
        }

        private void btnShowRpt_Click(object sender, EventArgs e)
        {
            Form5 f5 = new Form5();
            f5.Show();
        }

        private void xtraTabPage4_Paint(object sender, PaintEventArgs e)
        {

        }
        #endregion

        // method to update candidates

        /*
    private void UpdateCandidate()
    {
        try
        {
            // Queries
            //check for the ERP NO does it exist in DB
            string queryCheck = "select * from Candidate where ErpNo='" + txtCan1.Text + "'";

            // commands 
            SqlCommand cmd = new SqlCommand(queryCheck, con);

            // open connection
            con.Open();

            // execute command
            SqlDataReader rdr = cmd.ExecuteReader();

            while (rdr.Read())

            {
                // :Code here
            }
            // close connection so it can proceed further w/o conflicts
            //rdr.Close();

            // Now, trying to update the event time column into database.
            if (rdr.HasRows)
            {
                string update = "UPDATE Candidate SET EventTime = '" + DateTime.Now + "' WHERE ErpNo= '" + txtCan1.Text + "'";

                SqlCommand cmd1 = new SqlCommand(update, con);

                cmd.ExecuteNonQuery();

                con.Close();
                MessageBox.Show("Database Updated.", "Message");
            }
            else
            {
                // sql query
                string insert = "Name,FatherName,ErpNo,Class,Photo,GenderINSERT INTO Candidate (Name,FatherName,ErpNo,Class,Photo,Gender,@EventTime)SELECT Name,FatherName,ErpNo,Class,Photo,Gender FROM Students";

                // sql command
                SqlCommand command = new SqlCommand(insert,con);
                command.Parameters.AddWithValue("@EventTime",DateTime.Now);

                // execute command
                cmd.ExecuteNonQuery();
                con.Close();
                MessageBox.Show("Database Updated!", "Message"); 

            }
        }*/


    }
}