using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.SqlClient;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace VoteToHead
{
    public partial class Form4 : Form
    {
        public Form4()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
           // studentTableAdapter1.Fill(msdbDataSet31.Student);
        }

        private void Form4_Load(object sender, EventArgs e)
        {
            SqlConnection sqlconnect = new SqlConnection("Data Source=(LocalDB)\\MSSQLLocalDB;AttachDbFilename='|DataDirectory|\\Database\\VHDatabase.mdf';Integrated Security=True");
            SqlCommand cmd = new SqlCommand("select * from Candidate;",sqlconnect);
            SqlDataReader dr;
            try {

                sqlconnect.Open();
                dr = cmd.ExecuteReader();
                while (dr.Read())
                {
                    //this.chart1.Series["Votes"].Points.AddXY((dr[0].ToString("Name")), dr.GetInt32("Votes"));

                    this.chart1.Series["Votes"].Points.AddXY(dr.GetString(1), dr.GetInt32(8));
                    //this.chart1.Series["Votes"].Points.AddXY("Minahil",56);
                    //this.chart1.Series["Votes"].Points.AddXY("Anosha", 86);
                    //this.chart1.Series["Votes"].Points.AddXY("Sneha", 65);
            
                    //currentVotes.Add(int.Parse(reader[0].ToString()));
                }
            }
            catch (Exception ex)
            {
                MessageBox.Show(ex.ToString());
            }
            
        }
    }
}
